[project]
name = "rfdiffusion"
version = "2.5"
requires-python = ">=3.9,<3.12"
dependencies = [
    "hydra-core",
    "matplotlib",
    "omegaconf",
    "networkx",
    "numpy",
    "pandas",
    "pydantic",
    "pyrsistent",
    "scipy",
    "tqdm"
]
